server.port = 9091
spring.application.name = picc-mzmtb-server

#----------------Consul配置-------------
spring.cloud.consul.host = 127.0.0.1
spring.cloud.consul.port = 8500
spring.cloud.consul.discovery.register = true
#开关安全检测
spring.cloud.consul.discovery.health-check-enabled = true
# 延迟初始健康检查时间至 360 秒
spring.cloud.consul.discovery.health-check-delay = 360s
spring.cloud.consul.discovery.health-check-critical-timeout = 30s
spring.cloud.consul.discovery.health-check-url = http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
spring.cloud.consul.discovery.instance-id = ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring.cloud.consul.discovery.service-name = ${spring.application.name}
spring.cloud.consul.discovery.port = ${server.port}
spring.cloud.consul.discovery.prefer-ip-address = true
spring.cloud.consul.discovery.query-passing = true
spring.cloud.consul.discovery.acl-token = 17373549-c4b5-9d33-778d-d769382d5a7b
spring.cloud.consul.ribbon.enabled = true
spring.cloud.consul.retry.enable = true

#-------------------redis---------------------------------
spring.redis.host = 10.57.17.188
spring.redis.port = 8000
spring.redis.password = PICCmbgl@2024
spring.redis.database = 0
spring.redis.timeout = 30000
spring.redis.enable = true
spring.redis.lettuce.pool.max-active = 5
spring.redis.lettuce.pool.max-wait = -1ms
spring.redis.lettuce.pool.max-idle = 1
spring.redis.lettuce.pool.min-idle = 0
spring.redis.lettuce.cluster-topology-refresh-interval = 30000
management.health.redis.enabled = false

#-------------------jpa---------------------------------
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect
#spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql = true

#----------------datasource---------------------------------
spring.datasource.driver-class-name = com.huawei.opengauss.jdbc.Driver
spring.datasource.url = jdbc:opengauss://10.57.18.123:8000,10.57.18.6:8000,10.57.18.169:8000/paas_dev_cdm?targetServerType=master&currentSchema=cdm_dev_user
spring.datasource.username = cdm_dev_user
spring.datasource.password = Abaqb*kYeZ25cK%Tdx4
#测试数据库敏感数据加密使用的数据库
#spring.datasource.url = jdbc:opengauss://10.57.18.123:8000,10.57.18.6:8000,10.57.18.169:8000/paas_dev_cdm?targetServerType=master&currentSchema=cdm_test_user
#spring.datasource.username = cdm_test_user
#spring.datasource.password = 6fMbEOd71bX&T(-M
spring.datasource.hikari.minimum-idle = 5
spring.datasource.hikari.maximum-pool-size = 20
spring.datasource.hikari.maxActive = 100
spring.datasource.hikari.initialSize = 4
spring.datasource.hikari.filters = stat
spring.datasource.hikari.idle-timeout = 30000
spring.datasource.hikari.max-lifetime = 1800000
spring.datasource.hikari.connection-timeout = 30000
spring.datasource.test-on-return = true
spring.datasource.test-on-borrow = true
spring.datasource.test-on-connect = true

#-------------------activiti---------------------------------
#spring.activiti.jobExecutorActivate = true
spring.activiti.database-schema-update = false
spring.activiti.check-process-definitions = false
spring.activiti.async-executor-activate = false
spring.activiti.history-level = audit

#-------------------security---------------------------------
#所有响应头中添加X-Frame-Options: SAMEORIGIN
spring.security.frame-options = sameorigin

#-------------------mail-------------------------------------
#spring.mail.host = 10.35.237.85
#spring.mail.port = 25
#spring.mail.username = mzmtb.security@picchealth.com
#spring.mail.password = mGPgqW#ZNQ

#-------------------spring其他配置---------------------------
spring.main.allow-circular-references = true
spring.main.allow-bean-definition-overriding = true
spring.servlet.multipart.enabled = false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds = 7200000

#-------------------ribbon---------------------
ribbon.ConnectTimeout = 7200000
ribbon.ReadTimeout = 7200000

#---------------mvcInterceptorsList------------------
mvcInterceptorsList = /Doctor/**, /vipMbDeclareForProf/**, /ppop/**, /offline/**, /drugstore/**, /codename/**, /drugstoreDetailReport/**, /drugstoreOrderPrint/**, /drugstoreOrderReport/**, /MbDataList/**, /MbImport/**, /MbCardStatusReport/**, /MbInfoHistory/**, /mbmzInfoUpdate/**, /mbmzSendCard/**, /MbSettlementReport/**, /MbUpdate/**, /MbUser/**, /vipAccount/**, /vipAccountMbmzList/**, /VipChronicAccount/**, /MbDeclareExpertAssign/**, /MbDeclareFileView/**, /MbDeclareFirstTrial/**, /vipMbDeclarePhysicalAssign/**, /vipMbDeclareList/**, /vipMbDeclareReview/**, /mb/auditform/**, /MbExpertList/**, /vipMbmzStatusLogList/**, /vipOrgBankinfo/**, /PhysicalOrg/**, /hisClinicFeeList/**, /hisCreateCard/**, /hisManager/**, /hisRegister/**, /selfclaimInfoService/**, /selfclaimInvoiceDetail/**, /stlAuthinfo/**, /stlClinicbalanceinvoice/**, /vipDrugstoreOrderClaim/**, /vipInfo/**, /Login/checkLogin, /MbDeclare/**, /MbReview/**, /v2/**

#-------------mybaits------------------------------
mybatis.configuration.cache-enabled = false
mybatis.type-aliases-package = com.picchealth.module.*.dao
mybatis.mapper-locations = classpath*:mapper/**/*Dao.xml

#-------------------pagehelper---------------------
pagehelper.helperDialect = postgresql
pagehelper.params = count=countSql
pagehelper.reasonable = true
pagehelper.support-methods-arguments = true

#----------------------snowflow--------------------------
primarykey.snow.datacenterId = ${random.long(32)}
primarykey.snow.machineId = ${random.long(32)}
primarykey.partition.prefi = 1

#-----------------management------------------------------
management.endpoints.web.exposure.include = health

#-------------------flag---------------------
tokenInterceptFlag = true
#小程序签名校验
xcxInterceptFlag = false
#check.auditForm.flag = 0
isUseFeign = N
#获取体检报告信息：001-正式数据，002-测试数据
fileFlag = 001
#小程序签名有效时间
expireTime = 30

#---------------url----------------------------
JG004Url = http://47.104.155.55:8080/picc/services?wsdl
URL5000 = http://10.252.79.60:5000/
URL5001 = http://10.252.79.60:5001/
URL5002 = http://10.252.79.60:5002/
applicationUrl = http://10.57.17.188:10100/zt/mbgl-uat-ns-btc-hw-k8s/picc-mzmtb-gateway/call/service
urlSiteMap = http://api.guahao.com/renbaohealth/mobile_hospital/sitemap.xml
uploadFolder = /backend/logs/hmlink-server/mbslic/
httpUrlYLI = https://dev-h5-api-mtb.picchealth.com/appimg/mtb
httpurl = https://dev-h5-api-mtb.picchealth.com/appimg/mtb
icon.url = http://10.57.128.98:9966/imgs/

#------------------id/key----------------------------
sxyibao.channelId = ZESLIONEYURQNZQ53E0TWLH0UYAJMGRD
sxyibao.sm4Key = SOSHEY9DLBOW2QJK3IY4RM3AIDYNQUAD
yihuapi.appKey = 9000874
yihuapi.secret = ve86QX82F7u49eMMFSYHIs6626fd6GupI25P375Togo
wjx.appId = wxd947200f82267e58
wjx.path = pages/wjxqList/wjxqList
wjx.activityId = OtWXDmr
ocrWqx.app_key = bc8cb6e259014f8496deee26170f427f
ocrWqx.app_secret = e8fcfc10a1524a9ba88a40339ff3d364
sm4.sm4Key = 1234567812345678

#-------------------Medicare---------------------------------
Medicare.fixmedins_code = P61010400513
Medicare.fixmedins_name = 西安国宁药业有限公司第一分公司
Medicare.mdtrtarea_admvs = 610104
Medicare.opter = admin
Medicare.opter_name = 系统管理员
Medicare.opter_no = 1
Medicare.mac = 1
Medicare.ip = 1
Medicare.recer_sys_code = FSI_LOCAL
Medicare.infver = V1.0
Medicare.opter_type = 1
Medicare.ybflag = 1

SxMedicare.fixmedinsCode.BJ = R61030000001
SxMedicare.fixmedinsCode.SL = R61100000001
SxMedicare.fixmedinsCode.YA = R61060000001
SxMedicare.fixmedinsCode.YL = R61080000001
SxMedicare.fixmedinsCode.YLi = R61110000001
SxMedicare.fixmedinsCode.XYa = R61040000001
SxMedicare.fixmedinsName.BJ = 人保健康(宝鸡)
SxMedicare.fixmedinsName.SL = 人保健康(商洛)
SxMedicare.fixmedinsName.YA = 人保健康(延安)
SxMedicare.fixmedinsName.YL = 人保健康(榆林)
SxMedicare.fixmedinsName.YLi = 人保健康(杨凌)
SxMedicare.fixmedinsName.XYa = 人保健康(咸阳)
SxMedicare.devSafeInfo.BJ = RvbFFR/OqT1ICjcZnn7emMFEwMZZwZmj7b3W/sL0ud+PaOaNyBJhK7VXkIY6iUaaj14zlm+k0YSwjbhu2wClChHm+vlgDAL7mkdg85fzX3V3FqwLYMh9vGClBzqqQtOvv60f3THWhNazaIz6LK0CrLwTa3nXfs28gBj2rimAUNY=
SxMedicare.devSafeInfo.SL = dqfHoMV6WVpVhfCeWO5UJrLqbBtXZkzeBzoqVZ1GJJwD32c9uw+fghxDF9PmLaI4JMmoCIqPRsS+W6fUtHydKqsqq9YzbHK2AZWkfc8uE2Wh2ArmFMu08Tj0704I++P4gOhZjPR0kfCavakSQUvJgGxvX6URPhD7V9i7AJ3naRY=
SxMedicare.devSafeInfo.YA = L7w9hOvzTwOXKcmhhBS/4K/t9McWxt6mvausAafp8JjFJ2WArTSBzn0LkQ7Vv/qpx7VqvlMC4oz3D4X48cZcFBC/DtaH0DGea6KQTDSeJqriWWM2+VyKHHM4qYdJe0XiYyeaGVhKGYfAsDyOocvU2CmJB/QqA92ex6Yhj//h7Lc=
SxMedicare.devSafeInfo.YL = wj8LSIMGB4HpvcsXewansHKlM6iWayk6nr68tTUjYJDMIUa7AvTLhm5kP1Y3b1XxeBk/XKdMHa43jK7RIUEoJPxhjcw2cZ7TZjrYWdjeN/Kk9wMefrTEJz0HyzlwlISQJ+YRziA4Dv6GqS+oHr5Az+FnMRlTXfv2G/fGukbXqkw=
SxMedicare.devSafeInfo.YLi = kcF03A5O06SnYFbLnWBHJXMIq+K8fhbIHM2e1t2LNtLuZ9lmPR7Il793pRrOahf5IwxT+Kd8Tl3hoh9GNM7juGVuhy9XCMd7ixh/zWGb9zj2r0Tve8It3daKU0ACo7/xQiPQX0OdYjbx6P5pQ7CS6y+cpbRS69NBeL8gzi+gC7k=
SxMedicare.devSafeInfo.XYa = JlPf2AnYy/3E6mFYKEzu9j2fOPWhQn2AYOxWJoNyOGZYdR6LoxLd8SGhXlpMponuykFuqzY9LGPC/7ceUOIsYQPVpjeBolf9hZxNEuCTYCMcrkK5uk9kmOFB/TYxYC7vjPCNWMOLsHrtmYpTfgkzz/KXmCnlj8elJmNsvgyAc8E=
SxMedicare.timeout.read = 5000
SxMedicare.timeout.connect = 3000

#-------------------call---------------------------------
# 陕西医保测试地址
call.hosts.sxmedicare.host = http://10.223.1.46:80
# 文曲星身份证、户口本识别
call.hosts.ocrWqx.host = http://engine.group.ocr.cspiccnet:28121
# 短信
call.hosts.wssmsif.host = http://10.30.131.12:8000/WSSMSIF/services
# 健康档案
call.hosts.jkda.host = http://10.252.123.45:513/hfmsappli
# 健康商城
call.hosts.jksc.host = http://test-api-intranet-jkgltyzx.picchealth.com
# 文曲星处方识别
call.hosts.wqxout.host = http://10.57.17.188:80
# 财险共享处方池 外网出口ip为111.205.229.65
call.hosts.cxcf.host = http://10.57.128.98:9501
# 微信-公网
call.hosts.wx.host = http://10.57.128.98:9502
call.hosts.wxxcx.host = http://10.57.128.98:9502/sns/jscode2session
# 晋城-短信发送
call.hosts.ltmessage.host = http://10.57.128.98:9503
# 微信-腾讯慧眼云人脸识别
call.hosts.txface.host = http://10.57.128.98:9504
# 文曲星印章识别
call.hosts.wqxSeal.host = http://engine.group.ocr.cspiccnet:28121
# 新技术处图片质检(Image Quality Inspector)
call.hosts.xjsIQI.host = http://center.ai-platform.cspiccnet:32001
# 新技术处医疗影像分类(Medical Image Classifier)
call.hosts.xjsMIC.host = http://center.ai-platform.cspiccnet:32001
# 新技术处病案首页信息抽取(Medical Info Extraction)
call.hosts.xjsMIE.host = http://center.ai-platform.cspiccnet:32001
# 新技术处图片脱敏(Image Masking)
call.hosts.xjsMask.host = http://center.ai-platform.cspiccnet:32001

#-------------------ftp---------------------------------
ftp.ip = 10.252.68.236
ftp.port = 21
ftp.username = app
ftp.password = kJ070q@1fuYeL8lba
#申报材料
xcxftp.mbfilepath = /mbdeclare/mbfile/
#体检报告
xcxftp.PhysicalReportPath = /mbdeclare/tjbg/
#慢病导入
xcxftp.mbmz = /mbmz/
#慢病导入错误
xcxftp.mbmzError = /mbmz/error/
#慢病修改导入
xcxftp.mbmzUpdate = /mbmzupdate/
#慢病修改导入错误
xcxftp.mbmzUpdateError = /mbmzupdate/error/
#阜新慢病导入
xcxftp.fxMbMz = /mbmzsb/
#阜新慢病导入错误
xcxftp.fxMbMzError = /mbmzsb/error/
#医护同步医院定时任务保存图片ftp路径
xcxftp.supplierPath = /supplier/
#九江pdf保存路径
xcxftp.mbCredentialsPathJJ = /mbdeclare/credentials/JJ/
xcxftp.ip = 10.252.68.236
xcxftp.port = 21
xcxftp.username = app
ftp.path = /home/app/
sftp.port = 22
xcxftp.password = kJ070q@1fuYeL8lba
ftp.privatekey = sftpkey/csprivatekey.bem
xcxftp.path = /home/app/xcx/
xcxsftp.port = 22

#---------------------临时文件目录----------------------
tmp.imgpath = /tmp/imgpath/
tmp.file2img = /tmp/file2img/
tmp.zippath = /tmp/zippath/
tmp.xmlpath = /tmp/xmlpath/
tmp.uploadpath = /tmp/uploadpath/

#--------------------Jod--------------------------------
jodconverter.local.enabled = true
jodconverter.local.office-home = /opt/libreoffice7.0
jodconverter.local.port-numbers = 8100,8101,8102
jodconverter.local.max-tasks-per-process = 10

#---------------------微信接口配置----------------------
wx = http://10.57.128.98:9502/sns/jscode2session
WeiXinLentivirusAppId = wx6dcf59f0584ed5dc
WeiXinLentivirusSecret = 0d7b15f9050b3cdf0f84c165ec9a0d46
WeiXinMiniProgramGrantType = authorization_code
WeiXinLentivirusAppIdH5 = wx20187f26217bde68
WeiXinLentivirusSecretH5 = d30b7eb4f6468c6f8cc89ba0e5693552

#-------------------mail---------------------
mailsender.host = newmail.picchealth.com
mailsender.sender = eshop@picchealth.com
mailsender.password = pass@word1

#-----------------swagger---------------------------
#framework.swagger.basePackage = com.picchealth.module.**.api
#framework.swagger.title = 门诊慢特病业务管理信息系统
#framework.swagger.description = 门诊慢特病业务管理信息系统
#framework.swagger.termsOfServiceUrl = ${spring.cloud.client.ip-address}:${server.port}
#framework.swagger.contact.name = XXname
#framework.swagger.contact.url = ${spring.cloud.client.ip-address}:${server.port}
#framework.swagger.contact.email = xxxx@xxx.com
#framework.swagger.version = 1.0
#framework.swagger.operationParameters = [{name=token, description=用户令牌, required=false}]

#-----------------线程池配置---------------------------
# application.properties
threadPoolTaskExecutor.enabled = true
threadPoolConfig.corePoolSize = 5
threadPoolConfig.maxPoolSize = 10
threadPoolConfig.queueCapacity = 20
threadPoolConfig.keepAliveSeconds = 60
threadPoolConfig.rejectedExecutionHandler = CallerRunsPolicy

#-----------------商洛复审入口开启时间配置---------------------------
activity.start1 = 2025-09-01
activity.end = 2025-12-20

#------------------智能化相关配置-------------------
# 图片质检定时任务单次处理申报数据条数
iqiLimit = 10
# 新技术处图片质检接口清晰度阈值（0-1）
blurProbThreshold = 0.5
# 新技术处图片质检接口倾斜度阈值（1-180）
angleProbThreshold = 30
# 图片质检规则校验清晰度阈值(概率值求和取平均值)
blurProb = 0.8
# 图片质检规则校验倾斜度阈值(倾斜占比张数)
angleProb = 0.8
# 医疗影像分类定时任务单次处理申报数据条数
micLimit = 10
# 身份证识别定时任务单词处理申报数据条数
idcardLimit = 10
# 印章识别定时任务单词处理申报数据条数
sealLimit = 10
# 印章识别判定可信度概率阈值
sealScore = 0.8
call.hosts.xjsMRX.host = http://center.ai-platform.cspiccnet:32001
