server.port = 9093
spring.application.name = picc-mzmtb-auth

#----------------Consul配置-------------
spring.cloud.consul.host = 127.0.0.1
spring.cloud.consul.port = 8500
spring.cloud.consul.discovery.register = true
spring.cloud.consul.discovery.health-check-critical-timeout = 30s
spring.cloud.consul.discovery.health-check-url = http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
spring.cloud.consul.discovery.instance-id = ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring.cloud.consul.discovery.service-name = ${spring.application.name}
spring.cloud.consul.discovery.port = ${server.port}
spring.cloud.consul.discovery.prefer-ip-address = true
spring.cloud.consul.discovery.query-passing = true
spring.cloud.consul.discovery.acl-token = f0447373-e45c-65f7-2c5a-7839ab27de24
spring.cloud.consul.ribbon.enabled = true
spring.cloud.consul.retry.enable = true

#-------------------spring---------------------------------
spring.main.allow-circular-references = true
spring.servlet.multipart.enabled = false
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds = 7200000

#-------------------ribbon---------------------
ribbon.ConnectTimeout = 7200000
ribbon.ReadTimeout = 7200000

#-------------------redis---------------------------------
spring.redis.host = 10.57.17.188
spring.redis.port = 8000
spring.redis.password = PICCmbgl@2024
spring.redis.database = 0
spring.redis.timeout = 30000
spring.redis.enable = true
spring.redis.lettuce.pool.max-active = 5
spring.redis.lettuce.pool.max-wait = -1ms
spring.redis.lettuce.pool.max-idle = 1
spring.redis.lettuce.pool.min-idle = 0
management.health.redis.enabled = false

#----------------datasource---------------------------------
spring.datasource.driver-class-name = com.huawei.opengauss.jdbc.Driver
spring.datasource.url = jdbc:opengauss://10.57.18.123:8000,10.57.18.6:8000,10.57.18.169:8000/paas_dev_cdm?targetServerType=master&currentSchema=cdm_dev_user
spring.datasource.username = cdm_dev_user
spring.datasource.password = Abaqb*kYeZ25cK%Tdx4
spring.datasource.hikari.minimum-idle = 5
spring.datasource.hikari.maximum-pool-size = 20
spring.datasource.hikari.maxActive = 100
spring.datasource.hikari.initialSize = 4
spring.datasource.hikari.filters = stat
spring.datasource.hikari.idle-timeout = 30000
spring.datasource.hikari.max-lifetime = 1800000
spring.datasource.hikari.connection-timeout = 30000
spring.datasource.test-on-return = true
spring.datasource.test-on-borrow = true
spring.datasource.test-on-connect = true

#-------------mybaits------------------------------
mybatis.type-aliases-package = com.picchealth.module.*.dao
mybatis.mapper-locations = classpath*:mapper/**/*Dao.xml

#---------------jodconverter---------------------------
jodconverter.local.enabled = false
jodconverter.local.office-home = D:/LibreOffice
jodconverter.local.port-numbers = 8100
jodconverter.local.max-tasks-per-process = 100
jodconverter.local.workingDir = D:/LibreOfficeTest

#---------------mvcInterceptorsList------------------
mvcInterceptorsList = /Doctor/**, /vipMbDeclareForProf/**, /ppop/**, /offline/**, /drugstore/**, /codename/**, /drugstoreDetailReport/**, /drugstoreOrderPrint/**, /drugstoreOrderReport/**, /MbDataList/**, /MbImport/**, /MbCardStatusReport/**, /MbInfoHistory/**, /mbmzInfoUpdate/**, /mbmzSendCard/**, /MbSettlementReport/**, /MbUpdate/**, /MbUser/**, /vipAccount/**, /vipAccountMbmzList/**, /VipChronicAccount/**, /MbDeclareExpertAssign/**, /MbDeclareFileView/**, /MbDeclareFirstTrial/**, /vipMbDeclarePhysicalAssign/**, /vipMbDeclareList/**, /vipMbDeclareReview/**, /mb/auditform/**, /MbExpertList/**, /vipMbmzStatusLogList/**, /vipOrgBankinfo/**, /PhysicalOrg/**, /hisClinicFeeList/**, /hisCreateCard/**, /hisManager/**, /hisRegister/**, /selfclaimInfoService/**, /selfclaimInvoiceDetail/**, /stlAuthinfo/**, /stlClinicbalanceinvoice/**, /vipDrugstoreOrderClaim/**, /vipInfo/**, /Login/checkLogin, /MbDeclare/**, /MbReview/**, /v2/**

#-------------------pagehelper---------------------
pagehelper.helperDialect = postgresql
pagehelper.params = count=countSql
pagehelper.reasonable = true
pagehelper.support-methods-arguments = true

#-----------------swagger---------------------------
#swagger.basePackage = com.picchealth.module.**.api
#swagger.title =门诊慢特病业务管理信息系统-鉴权服务
#swagger.description =门诊慢特病业务管理信息系统-鉴权服务
#swagger.termsOfServiceUrl = ${spring.cloud.client.ip-address}:${server.port}
#swagger.contact.name = XXname
#swagger.contact.url = ${spring.cloud.client.ip-address}:${server.port}
#swagger.contact.email = xxxx@xxx.com
#swagger.version = 1.0
#swagger.operationParameters = [{name=token, description=用户令牌, required=false}]

#------------------id/key----------------------------
primarykey.snow.datacenterId = ${random.long(32)}
primarykey.snow.machineId = ${random.long(32)}
primarykey.partition.prefi = 1
forwardUrl = http://10.57.17.188:10101/zt/mbgl-uat-ns-btc-hw-k8s/picc-mzmtb-server/

#------------------email----------------------------
spring.mail.host = smtp.qq.com
spring.mail.port = 587
spring.mail.username = 1579282425@qq.com
spring.mail.password = fdbmecbvlejwiedi
spring.mail.properties.mail.smtp.auth = true
spring.mail.properties.mail.smtp.starttls.enable = true
spring.mail.properties.mail.smtp.starttls.required = true
spring.mail.properties.mail.smtp.ssl.enable = true
spring.mail.properties.mail.smtp.socketFactory.port = 587
spring.mail.properties.mail.smtp.socketFactory.fallback = false
emailurl = http://127.0.0.1:8080/#/resetConfirm

#--------key--------------------
sm4.sm4Key = 1234567812345678
tokenInterceptFlag = true
