server.port = 9001
spring.application.name = picc-mzmtb-gateway

#------------tongweb配置-------------
server.tongweb.license.type = file
server.tongweb.license.path = classpath:license.dat

#----------------Consul配置-------------
spring.cloud.consul.host = 127.0.0.1
spring.cloud.consul.port = 8500
spring.cloud.consul.discovery.register = true
spring.cloud.consul.discovery.health-check-critical-timeout = 30s
spring.cloud.consul.discovery.health-check-url = http://${spring.cloud.client.ip-address}:${server.port}/actuator/health
spring.cloud.consul.discovery.instance-id = ${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
spring.cloud.consul.discovery.service-name = ${spring.application.name}
spring.cloud.consul.discovery.port = ${server.port}
spring.cloud.consul.discovery.prefer-ip-address = true
spring.cloud.consul.discovery.query-passing = true
spring.cloud.consul.discovery.acl-token = f0447373-e45c-65f7-2c5a-7839ab27de24
spring.cloud.consul.ribbon.enabled = true
spring.cloud.consul.retry.enable = true

#---------------spring------------------------
spring.http.multipart.maxFileSize = 50MB
spring.http.multipart.maxRequestSize = 100MB
spring.servlet.multipart.maxFileSize = 50MB
spring.servlet.multipart.maxRequestSize = 100MB
spring.main.allow-bean-definition-overriding = true
management.endpoints.web.exposure.include = health

#---------------redis------------------------
spring.redis.host = 10.57.17.188
spring.redis.port = 8000
spring.redis.password = PICCmbgl@2024
spring.redis.database = 0
spring.redis.timeout = 30000
spring.redis.enable = true
spring.redis.lettuce.pool.max-active = 8
spring.redis.lettuce.pool.max-wait = -1ms
spring.redis.lettuce.pool.max-idle = 8
spring.redis.lettuce.pool.min-idle = 0
management.health.redis.enabled = false

#--------------------xxljob-------------------------------
xxl.job.admin.addresses = http://10.57.17.188:8070
xxl.job.accessToken = Pass@word1
xxl.job.executor.appname = xxl-job-executor-mzmtb
xxl.job.executor.address =
xxl.job.executor.ip =
xxl.job.executor.port = 9999
xxl.job.executor.logpath = /data/applogs/xxl-job/jobhandler
xxl.job.executor.logretentiondays = 30

#----------------url/flag/code/key-------------------------
forwardUrl = http://10.57.17.188:10101/zt/mbgl-uat-ns-btc-hw-k8s/picc-mzmtb-server/
zuul.inside.url = http://10.57.17.188:10101
zuul.hmlink.server.url = /zt/mbgl-uat-ns-btc-hw-k8s/picc-mzmtb-server/
call.cache-class-name = applicationCallCache
code = 0011754
reportFlag = true
jksc.infokey = 04cbbb5ea32eb0b1efcec2f2cb82e00561a14a53d75f642df7d6283675aeeabd8905d7169467ed6cee8f6d3462786059fc5393cde2f1d05e0b4c7654768cff7b10
jksc.phonekey = 0405baf05424a8e807e9e1ecf6d2d2f23f44adc5dad43ab1d171657b2c32d4912361498842fddcbad7d9991f1ffac35c70b89a4b7cc0f26994a08c3cc51cc8bf75
jksc.userSource = 135
jksc.channelCode = 1016

#--------------ftp-----------------------------
ftp.ip = 10.252.68.236
ftp.port = 21
ftp.username = app
ftp.password = kJ070q@1fuYeL8lba
ftp.mbeditpath = /mbdeclare/mbedit/
xcxftp.ip = 10.252.68.236
xcxftp.port = 21
xcxftp.username = app
xcxftp.password = kJ070q@1fuYeL8lba
xcxftp.path = /home/app/xcx/

#--------------httpclient--------------------
httpclient.maxTotal = 200
httpclient.maxPerRoute = 100
httpclient.socketTimeout = 200000
httpclient.connectTimeout = 100000
httpclient.requestTimeout = 100000

#----------------swagger------------------
#swagger.basePackage = com.picchealth.module.**.api
#swagger.title = 慢病管理系统-前台服务
#swagger.description = 慢病管理系统-前台服务swagger
#swagger.termsOfServiceUrl = ${spring.cloud.client.ip-address}:${server.port}
#swagger.contact.name = 慢病管理系统-前台服务
#swagger.contact.url = http://xxxx.com
#swagger.contact.email = xxxx@xxx.com
#swagger.version = 1.0
#swagger.operationParameters = [{name=token, description=用户令牌, required=false}]

#----------------path------------------
tmp.imgpath = /tmp/imgpath/
tmp.file2img = /tmp/file2img/
tmp.zippath = /tmp/zippath/
tmp.xmlpath = /tmp/xmlpath/
tmp.uploadpath = /tmp/uploadpath/
logs.path = /logs/path

#---------------配置文件--------------------
logging.level.root = INFO
logging.level.org.springframework.cloud.sleuth = DEBUG
logging.level.com.netflix = DEBUG
logging.path = /logs
logging.config = classpath:logback-spring.xml
